# Generated by Django 3.2.5 on 2021-07-19 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_delete_coach'),
        ('teams', '0002_auto_20210708_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='roster_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.rosterteam'),
        ),
    ]
