# Generated by Django 3.2.5 on 2021-08-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_team_big_guy_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='big_guy',
            field=models.BooleanField(default=False),
        ),
    ]
