# Generated by Django 3.2.5 on 2021-08-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0014_auto_20210830_1548'),
        ('teams', '0010_auto_20210830_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='roster_player',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='roster.rosterplayer'),
        ),
    ]
