# Generated by Django 3.2.5 on 2021-09-03 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20210903_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='complete',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
