# Generated by Django 3.2.5 on 2021-09-07 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20210907_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='dead',
        ),
        migrations.RemoveField(
            model_name='team',
            name='missing_next_game',
        ),
        migrations.RemoveField(
            model_name='team',
            name='niggling_injury',
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='dead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='missing_next_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='niggling_injury',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
