# Generated by Django 3.2.5 on 2021-09-08 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_auto_20210907_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='player_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
