# Generated by Django 3.2.5 on 2021-09-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_teamplayer_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='fired',
            field=models.BooleanField(default=False),
        ),
    ]
