# Generated by Django 3.2.5 on 2021-09-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_auto_20210920_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='level',
            field=models.CharField(choices=[('NONE', 'NONE'), ('EXPERIENCED', 'EXPERIENCED'), ('VETERAN', 'VETERAN'), ('EMERGING STAR', 'EMERGING STAR'), ('STAR', 'STAR'), ('SUPER STAR', 'SUPER STAR'), ('LEGEND', 'LEGEND')], default='NONE', max_length=20),
        ),
    ]
