# Generated by Django 3.2.5 on 2021-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0015_skill_random_identifier'),
        ('teams', '0020_teamplayer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='extra_skills',
            field=models.ManyToManyField(blank=True, related_name='extra_skills', to='roster.Skill'),
        ),
    ]
