# Generated by Django 3.2.5 on 2021-09-29 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_teamplayer_extra_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='total_mvp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
