# Generated by Django 3.2.5 on 2021-10-01 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_teamplayer_total_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
