# Generated by Django 3.2.5 on 2021-10-08 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0023_team_league_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='spent_spp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
