# Generated by Django 3.2.5 on 2021-10-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0025_teamplayer_number_of_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_journeyman',
            field=models.BooleanField(default=False),
        ),
    ]
