# Generated by Django 3.2.5 on 2021-10-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0026_team_is_journeyman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_journeyman',
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='is_journeyman',
            field=models.BooleanField(default=False),
        ),
    ]
