# Generated by Django 3.2.5 on 2021-11-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20211011_1635'),
        ('teams', '0027_auto_20211015_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.season'),
        ),
    ]
