# Generated by Django 3.2.5 on 2021-12-02 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0028_team_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='armor_value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
    ]
