# Generated by Django 3.2.5 on 2021-12-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0029_alter_teamplayer_armor_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
