from django.urls import path
from . import views

app_name = 'teams'

urlpatterns = [
    path('index/', views.index_test, name='index_test'),
    path('', views.AllTeamListView.as_view(), name='all_teams'),
    path('all_ready_teams/', views.AllReadyTeamListView.as_view(), name='all_ready_teams'),
    path('<int:pk>/', views.AllTeamDetail.as_view(), name='all_team_detail'),
    path('my_teams/', views.MyTeamsListView.as_view(), name='my_teams'),
    path('my_retired_teams/', views.MyRetiredTeamsListView.as_view(), name='my_retired_teams'),
    path('my_teams/create', views.get_create_my_team, name='create_my_team'),
    path('my_teams/dismiss/<int:pk>/', views.dismiss_team, name='dismiss_team'),
    path('my_teams/preapre/<int:pk>/', views.prepare_team, name='prepare_team'),
    path('my_teams/ready/<int:pk>/', views.ready_team, name='ready_team'),
    path('my_teams/buy_player/<int:team_id>', views.buy_player, name='buy_player'),
    path('my_teams/fire_player/<int:team_id>', views.fire_player, name='fire_player'),
    path('my_teams/detail/<int:team_id>', views.my_team_detail, name='my_team_detail'),
    path('my_teams/buy_re_roll/<int:team_id>', views.buy_re_roll, name='buy_re_roll'),
    path('my_teams/remove_re_roll/<int:team_id>', views.remove_re_roll, name='remove_re_roll'),
    path('my_teams/buy_assistant_coach/<int:team_id>', views.buy_assistant_coach, name='buy_assistant_coach'),
    path('my_teams/remove_assistant_coach/<int:team_id>', views.remove_assistant_coach, name='remove_assistant_coach'),
    path('my_teams/buy_cheerleader/<int:team_id>', views.buy_cheerleader, name='buy_cheerleader'),
    path('my_teams/remove_cheerleader/<int:team_id>', views.remove_cheerleader, name='remove_cheerleader'),
    path('my_teams/buy_extra_fan/<int:team_id>', views.buy_extra_fan, name='buy_extra_fan'),
    path('my_teams/remove_extra_fan/<int:team_id>', views.remove_extra_fan, name='remove_extra_fan'),
    path('my_teams/buy_apothecary/<int:team_id>', views.buy_apothecary, name='buy_apothecary'),
    path('my_teams/remove_apothecary/<int:team_id>', views.remove_apothecary, name='remove_apothecary'),
    path('my_teams/manage_player/<int:team_id>', views.manage_player, name='manage_player'),
    path('my_teams/manage_player/change_name_number', views.change_player_name_number, name='change_player_name_number'),
    path('my_teams/manage_player/fire_player/<int:team_id>', views.manage_fire_player, name='manage_fire_player'),

    path('my_teams/manage_team/buy_re_roll/<int:team_id>', views.manage_buy_re_roll, name='manage_buy_re_roll'),
    path('my_teams/manage_team/remove_re_roll/<int:team_id>', views.manage_remove_re_roll, name='manage_remove_re_roll'),
    path('my_teams/manage_team/buy_assistant_coach/<int:team_id>', views.manage_buy_assistant_coach,
         name='manage_buy_assistant_coach'),
    path('my_teams/manage_team/remove_assistant_coach/<int:team_id>', views.manage_remove_assistant_coach,
         name='manage_remove_assistant_coach'),
    path('my_teams/manage_team/buy_cheerleader/<int:team_id>', views.manage_buy_cheerleader, name='manage_buy_cheerleader'),
    path('my_teams/manage_team/remove_cheerleader/<int:team_id>', views.manage_remove_cheerleader,
         name='manage_remove_cheerleader'),
    path('my_teams/manage_team/buy_apothecary/<int:team_id>', views.manage_buy_apothecary, name='manage_buy_apothecary'),
    path('my_teams/manage_team/remove_apothecary/<int:team_id>', views.manage_remove_apothecary,
         name='manage_remove_apothecary'),
    path('my_teams/manage_team/buy_player.py/<int:team_id>', views.manage_buy_player, name='manage_buy_player'),
    path('my_teams/manage_team/levelup/<int:player_id>', views.player_level_up, name='player_level_up'),
    path('my_teams/manage_team/levelup/first_random/<int:player_id>', views.random_first_skill, name='random_first_skill'),
    path('my_teams/manage_team/levelup/second_random/<int:player_id>', views.random_second_skill, name='random_second_skill'),
    path('my_teams/manage_team/levelup/choose_first/<int:player_id>', views.select_first_skill, name='select_first_skill'),
    path('my_teams/manage_team/levelup/choose_secondary/<int:player_id>', views.select_second_skill,
         name='select_second_skill'),
    path('my_teams/create_pdf/<int:team_id>', views.render_pdf_view, name='create_pdf'),
    path('my_teams/manage_team/confirm_journeyman/<int:team_id>', views.confirm_journeyman, name='confirm_journeyman')
]
