from django.urls import path
from .views import (
    AllTeamListView,
    AllReadyTeamListView,
    AllTeamDetail,
    MyTeamsListView,
    MyRetiredTeamsListView,
    get_create_my_team,
    dismiss_team,
    prepare_team,
    ready_team,
    buy_player,
    fire_player,
    my_team_detail,
    buy_re_roll,
    remove_re_roll,
    buy_assistant_coach,
    remove_assistant_coach,
    buy_cheerleader,
    remove_cheerleader,
    buy_extra_fan,
    remove_extra_fan,
    buy_apothecary,
    remove_apothecary,
    manage_player,
    change_player_name_number,
    manage_fire_player,
    manage_buy_re_roll,
    manage_remove_re_roll,
    manage_buy_assistant_coach,
    manage_remove_assistant_coach,
    manage_buy_cheerleader,
    manage_remove_cheerleader,
    manage_buy_apothecary,
    manage_remove_apothecary,
    manage_buy_player,
    player_level_up,
    index_test,
    random_first_skill,
    random_second_skill,
    select_first_skill,
    select_second_skill,
)

app_name = 'teams'

urlpatterns = [
    path('index/', index_test, name='index_test'),
    path('', AllTeamListView.as_view(), name='all_teams'),
    path('all_ready_teams/', AllReadyTeamListView.as_view(), name='all_ready_teams'),
    path('<int:pk>/', AllTeamDetail.as_view(), name='all_team_detail'),
    path('my_teams/', MyTeamsListView.as_view(), name='my_teams'),
    path('my_retired_teams/', MyRetiredTeamsListView.as_view(), name='my_retired_teams'),
    path('my_teams/create', get_create_my_team, name='create_my_team'),
    path('my_teams/dismiss/<int:pk>/', dismiss_team, name='dismiss_team'),
    path('my_teams/preapre/<int:pk>/', prepare_team, name='prepare_team'),
    path('my_teams/ready/<int:pk>/', ready_team, name='ready_team'),
    path('my_teams/buy_player/<int:team_id>', buy_player, name='buy_player'),
    path('my_teams/fire_player/<int:team_id>', fire_player, name='fire_player'),
    path('my_teams/detail/<int:team_id>', my_team_detail, name='my_team_detail'),
    path('my_teams/buy_re_roll/<int:team_id>', buy_re_roll, name='buy_re_roll'),
    path('my_teams/remove_re_roll/<int:team_id>', remove_re_roll, name='remove_re_roll'),
    path('my_teams/buy_assistant_coach/<int:team_id>', buy_assistant_coach, name='buy_assistant_coach'),
    path('my_teams/remove_assistant_coach/<int:team_id>', remove_assistant_coach, name='remove_assistant_coach'),
    path('my_teams/buy_cheerleader/<int:team_id>', buy_cheerleader, name='buy_cheerleader'),
    path('my_teams/remove_cheerleader/<int:team_id>', remove_cheerleader, name='remove_cheerleader'),
    path('my_teams/buy_extra_fan/<int:team_id>', buy_extra_fan, name='buy_extra_fan'),
    path('my_teams/remove_extra_fan/<int:team_id>', remove_extra_fan, name='remove_extra_fan'),
    path('my_teams/buy_apothecary/<int:team_id>', buy_apothecary, name='buy_apothecary'),
    path('my_teams/remove_apothecary/<int:team_id>', remove_apothecary, name='remove_apothecary'),
    path('my_teams/manage_player/<int:team_id>', manage_player, name='manage_player'),
    path('my_teams/manage_player/change_name_number', change_player_name_number, name='change_player_name_number'),
    path('my_teams/manage_player/fire_player/<int:team_id>', manage_fire_player, name='manage_fire_player'),

    path('my_teams/manage_team/buy_re_roll/<int:team_id>', manage_buy_re_roll, name='manage_buy_re_roll'),
    path('my_teams/manage_team/remove_re_roll/<int:team_id>', manage_remove_re_roll, name='manage_remove_re_roll'),
    path('my_teams/manage_team/buy_assistant_coach/<int:team_id>', manage_buy_assistant_coach,
         name='manage_buy_assistant_coach'),
    path('my_teams/manage_team/remove_assistant_coach/<int:team_id>', manage_remove_assistant_coach,
         name='manage_remove_assistant_coach'),
    path('my_teams/manage_team/buy_cheerleader/<int:team_id>', manage_buy_cheerleader, name='manage_buy_cheerleader'),
    path('my_teams/manage_team/remove_cheerleader/<int:team_id>', manage_remove_cheerleader,
         name='manage_remove_cheerleader'),
    path('my_teams/manage_team/buy_apothecary/<int:team_id>', manage_buy_apothecary, name='manage_buy_apothecary'),
    path('my_teams/manage_team/remove_apothecary/<int:team_id>', manage_remove_apothecary,
         name='manage_remove_apothecary'),
    path('my_teams/manage_team/buy_player/<int:team_id>', manage_buy_player, name='manage_buy_player'),
    path('my_teams/manage_team/levelup/<int:player_id>', player_level_up, name='player_level_up'),
    path('my_teams/manage_team/levelup/first_random/<int:player_id>', random_first_skill, name='random_first_skill'),
    path('my_teams/manage_team/levelup/second_random/<int:player_id>', random_second_skill, name='random_second_skill'),
    path('my_teams/manage_team/levelup/choose_first/<int:player_id>', select_first_skill, name='select_first_skill'),
    path('my_teams/manage_team/levelup/choose_secondary/<int:player_id>', select_second_skill,
         name='select_second_skill')
]
