# Generated by Django 3.2.5 on 2021-07-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LpcManager', '0002_rosterplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
