# Generated by Django 3.2.5 on 2021-07-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LpcManager', '0003_auto_20210701_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trait',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
