# Generated by Django 3.2.5 on 2021-07-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LpcManager', '0007_coach'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
