# Generated by Django 3.2.5 on 2021-10-11 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('CLOSED', 'CLOSED'), ('OPEN', 'OPEN')], max_length=20)),
                ('managers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_managers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
