# Generated by Django 3.2.5 on 2021-10-11 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('CLOSED', 'CLOSED'), ('OPEN', 'OPEN')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='league',
            name='managers',
        ),
        migrations.AddField(
            model_name='league',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('CLOSED', 'CLOSED'), ('OPEN', 'OPEN')], max_length=20)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='league.season')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='league.league'),
        ),
    ]
