# Generated by Django 3.2.5 on 2021-11-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0028_team_season'),
        ('league', '0002_auto_20211011_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='team',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
