# Generated by Django 3.2.5 on 2021-11-05 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0028_team_season'),
        ('league', '0003_tournament_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTeamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('loss', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tie', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_touchdown', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_cas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('league_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='league.tournament')),
            ],
        ),
    ]
