# Generated by Django 3.2.5 on 2021-11-05 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_auto_20210925_2157'),
        ('league', '0004_tournamentteamresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='match.match'),
        ),
    ]
