# Generated by Django 3.2.5 on 2021-11-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_tournament_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='match',
        ),
    ]
