# Generated by Django 3.2.5 on 2021-07-01 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agility', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('armor_value', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)])),
                ('max_quantity', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)])),
                ('min_quantity', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)])),
                ('movement_allowance', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('passing', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('position', models.CharField(max_length=50)),
                ('strength', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('primary_skills', models.ManyToManyField(related_name='primary_skills', to='roster.Skill')),
                ('secondary_skills', models.ManyToManyField(related_name='secondary_skills', to='roster.Skill')),
                ('traits', models.ManyToManyField(to='roster.Trait')),
            ],
        ),
    ]
