# Generated by Django 3.2.5 on 2021-07-01 15:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_auto_20210701_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterplayer',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='roster.Skill'),
        ),
        migrations.CreateModel(
            name='RosterTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apothecary', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('re_roll_cost', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)])),
                ('re_roll_max', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)])),
                ('special_rules', models.CharField(max_length=50)),
                ('tier', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.race')),
            ],
        ),
        migrations.AddField(
            model_name='rosterplayer',
            name='roster_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roster.rosterteam'),
            preserve_default=False,
        ),
    ]
