# Generated by Django 3.2.5 on 2021-07-23 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_delete_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterplayer',
            name='roster_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_players', to='roster.rosterteam'),
        ),
    ]
