# Generated by Django 3.2.5 on 2021-07-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_alter_rosterplayer_roster_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rosterplayer',
            name='primary_skills',
        ),
        migrations.AddField(
            model_name='rosterplayer',
            name='primary_skills',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.RemoveField(
            model_name='rosterplayer',
            name='secondary_skills',
        ),
        migrations.AddField(
            model_name='rosterplayer',
            name='secondary_skills',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
