# Generated by Django 3.2.5 on 2021-08-30 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_remove_rosterplayer_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterplayer',
            name='big_guy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rosterteam',
            name='big_guy_max',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
