# Generated by Django 3.2.5 on 2021-08-30 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_auto_20210830_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterplayer',
            name='armor_value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rosterteam',
            name='big_guy_max',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)]),
        ),
    ]
