# Generated by Django 3.2.5 on 2021-09-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0014_auto_20210830_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='random_identifier',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
