# Generated by Django 3.2.5 on 2021-09-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0015_skill_random_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterplayer',
            name='is_journeyman',
            field=models.BooleanField(default=False),
        ),
    ]
