# Generated by Django 3.2.5 on 2021-07-26 07:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0006_alter_team_extra_dedicated_fan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('first_team_td', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('second_team_td', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='teams.team')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='teams.team')),
            ],
        ),
    ]
