# Generated by Django 3.2.5 on 2021-09-20 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_teamplayer_fired'),
        ('match', '0007_auto_20210905_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayerMatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('died', models.BooleanField(default=False)),
                ('touchdown', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('badly_hart', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('seriously_injury', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kill', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('deflection', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('complete', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_cas', models.CharField(default='', max_length=100)),
                ('last_injury', models.CharField(default='', max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_match_record', to='match.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_player_record', to='teams.teamplayer')),
            ],
        ),
    ]
