# Generated by Django 3.2.5 on 2021-09-20 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_teamplayermatchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayermatchrecord',
            name='intercept',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='teamplayermatchrecord',
            name='total_cas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
