# Generated by Django 3.2.5 on 2021-09-20 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_auto_20210920_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayermatchrecord',
            name='seriously_hurt',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='teamplayermatchrecord',
            name='last_injury',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
