# Generated by Django 3.2.5 on 2021-09-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_auto_20210920_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_date',
        ),
        migrations.AddField(
            model_name='match',
            name='match_date_from',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_date_to',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
