# Generated by Django 3.2.5 on 2021-12-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='freeze_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
